### ISSUE TITLE
[Tip] Don't use pySmartDL lib

### ISSUE THREAD

**Issue by PrathamH** [monuyadav016/Saavn-Downloader#10]
I saw your problems with pySmartDL. Thought of asking a good friend of mine and an experienced coder for solution on it. He suggests to use requests and tqdm instead of pySmartDL. Also to use requests and tqdm lib while chunking the files instead of reading them into memory at once. Though I'm not a coder I believe my friend has given you right solution for this. Hope to see this program progress further.

**Comment by monuyadav016** [comment]
Tried a few solutions earlier but will look into it again. Also it's difficult to find songs where it is sure to run into problems.

**Comment by PrathamH** [comment]
If you want more assistance on this you can have a conversation with my friend Sorrow446 (Creator of Ti-DL and Qo-DL) on reddit.

**Comment by monuyadav016** [comment]
Thank you. I'll be glad if that issue is resolved so that the program is more robust.

**Comment by monuyadav016** [comment]
> If you want more assistance on this you can have a conversation with my friend Sorrow446 (Creator of Ti-DL and Qo-DL) on reddit.

Unfortunately I couldn't find anyone by that username on reddit.

**Comment by PrathamH** [comment]
> > If you want more assistance on this you can have a conversation with my friend Sorrow446 (Creator of Ti-DL and Qo-DL) on reddit.
> 
> Unfortunately I couldn't find anyone by that username on reddit.

https://www.reddit.com/user/Sorrow446/
