### ISSUE TITLE
Downloading individual songs

### ISSUE THREAD

**Issue by microtechton** [monuyadav016/Saavn-Downloader#12]
It would be a great feature if we could download individual songs using the song link rather than downloading the entire album and deleting the music we don't want.

**Comment by adimrsingh** [comment]
Did you found the songid from song url ? 

(Ex: https://www.saavn.com/s/song/english/Born-To-Die---The-Paradise-Edition/Summertime-Sadness/GBhaXiF8ZFw?)

**Comment by monuyadav016** [comment]
I've been giving a thought about this feature. The only issue is that is unreliable and fails to obtain the download url at times.

> Did you found the songid from song url ?
> 
> (Ex: https://www.saavn.com/s/song/english/Born-To-Die---The-Paradise-Edition/Summertime-Sadness/GBhaXiF8ZFw?)

The song_id can be obtained by inspecting the share button of the song. Obtaining the song_id not the deal here.

**Comment by adimrsingh** [comment]
> The song_id can be obtained by inspecting the share button of the song. Obtaining the song_id not the deal here.

Are you sure ? cause Api outputs nothing feeding the song_id obtained from the share button.

**Comment by monuyadav016** [comment]
> 
> Are you sure ? cause Api outputs nothing feeding the song_id obtained from the share button.

I know the API doesn't respond but that is the proper song id. So I'm to get the get the download url just the way it is retrieved by their website.

**Comment by monuyadav016** [comment]
> It would be a great feature if we could download individual songs using the song link rather than downloading the entire album and deleting the music we don't want.

The requested feature has been added. Download the latest update. Also refer to the updated [README](https://github.com/monuyadav016/Saavn-Downloader/blob/master/README.md) file for documentation and usage.
