### ISSUE TITLE
cannot fetch artist albums and songs

### ISSUE THREAD

**Issue by saptarshi1701057** [monuyadav016/Saavn-Downloader#13]
all the three lines to download songs from an artist are throwing errors 
errors thrown are attached below:-

saptarshi@saptarshi:~/Saavn-Downloader$ python Download.py -artist -album
  File "Download.py", line 54
    async def fetch(url, session):
            ^
SyntaxError: invalid syntax
saptarshi@saptarshi:~/Saavn-Downloader$ python Download.py -artist -album -fast
  File "Download.py", line 54
    async def fetch(url, session):
            ^
SyntaxError: invalid syntax
saptarshi@saptarshi:~/Saavn-Downloader$ python Download.py -artist -song
  File "Download.py", line 54
    async def fetch(url, session):
            ^
SyntaxError: invalid syntax

**Comment by monuyadav016** [comment]
I cloned the repo and tested it. Works just the way it should. If you have changed anything in the script, consider downloading this script again.

**Comment by saptarshi1701057** [comment]
i also freshly cloned the repo but i am still getting same error
$ python Download.py -artist -album
  File "Download.py", line 54
    async def fetch(url, session):
            ^
SyntaxError: invalid syntax

**Comment by saptarshi1701057** [comment]
brother i figured it out myself i was using python 2 instead of 3
