### ISSUE TITLE
Audio downloaded at only 96kbps

### ISSUE THREAD

**Issue by microtechton** [monuyadav016/Saavn-Downloader#14]
Not a big deal, but seems like you had forgotten to uncomment  `# dec_url = dec_url.replace('_96.mp4', '_320.mp4')` again.

**Comment by monuyadav016** [comment]
> Not a big deal, but seems like you had forgotten to uncomment `# dec_url = dec_url.replace('_96.mp4', '_320.mp4')` again.

Unfortunately yes. Thank you for the spontaneous response. I messed up my tests by changing the folder structure and so I couldn't run the tests to know that.
