### ISSUE TITLE
About using M4A...

### ISSUE THREAD

**Issue by Rajwadkar07** [monuyadav016/Saavn-Downloader#20]
Sir, I'd like to ask you to keep the audio format to mp3 because if you look into the spectrograph of the music generated by your code its frequencies are capped at 20KHz which is generally done in MP3. M4A whereas, uses advanced audio codec which doesn't cap the frequencies at 20KHz. Below are the examples of spectrograph for better understanding -
1. Saavn Downloader : [IMGUR](https://imgur.com/AMEmtca)
2. iTunes Plus : [IMGUR](https://imgur.com/DQWIprW)

**Comment by monuyadav016** [comment]
@Rajwadkar07 I would appreciate more help in understanding this concept.

**Comment by microtechton** [comment]
> Sir, I'd like to ask you to keep the audio format to mp3 because if you look into the spectrograph of the music generated by your code its frequencies are capped at 20KHz which is generally done in MP3. M4A whereas, uses advanced audio codec which doesn't cap the frequencies at 20KHz. Below are the examples of spectrograph for better understanding -
> 
> 1. Saavn Downloader : [IMGUR](https://imgur.com/AMEmtca)
> 2. iTunes Plus : [IMGUR](https://imgur.com/DQWIprW)

What tool did you use to download the iTunes Plus music?

**Comment by saptarshi1701057** [comment]
i saw it myself but problem is in jio savaan itself all the premium audio songs that you download are capped to 20 khz that's why their is no issue with the repo
