### ISSUE TITLE
download links from text file

### ISSUE THREAD

**Issue by L0nelyW0lf** [monuyadav016/Saavn-Downloader#21]
bro is there an option to put all the links in a text file and download them

**Comment by adimrsingh** [comment]
That can be done easily, but the downloaded file from the link will not contain mete-data (tags).

**Comment by monuyadav016** [comment]
@L0nelyW0lf You can specify urls in a text file using [-f or --file](https://github.com/monuyadav016/Saavn-Downloader#if-you-have-more-than-1-url-and-no-time-to-wait-use-the--f-or---file-argument-to-specify-the-absolute-path-to-txt-file-with-urls-pasted-line-by-line) argument in the command line.



> That can be done easily, but the downloaded file from the link will not contain meta-data (tags).

@adimrsingh That doesn't happen at all. Have you been facing any issues with -f flag?

**Comment by adimrsingh** [comment]
> @adimrsingh That doesn't happen at all. Have you been facing any issues with -f flag?

My bad, no issues with the -f flag. 'Not a MP4 File' error got triggered for those songs.

**Comment by L0nelyW0lf** [comment]
thanks bro
