### ISSUE TITLE
Error Downloading All songs

### ISSUE THREAD

**Issue by xambu** [monuyadav016/Saavn-Downloader#23]
python3 download_reloaded.py -album 
Enter the URL : https://www.jiosaavn.com/artist/atif-aslam-songs/MXn8bhT308U_
Downloading all albums for the Artist
Total Albums of the Artist: 282
Total requests: 29
Getting Album page: 0
...
...
Getting Album page: 27
Getting Album page: 28
Total Number of Albums found: 282
Initiating Album Download
Album name:  Batti Gul Meter Chalu
Downloading Gold Tamba.m4a
Error getting album with ID: 13673989
Initiating Album Download
...
...
None of the songs are downloaded

**Comment by monuyadav016** [comment]
@xambu I have tried that url and all seems to be working fine. As mentioned in README, you can retry when facing issues at times.
