### ISSUE TITLE
error occuring while downloading some songs

### ISSUE THREAD

**Issue by cs-mshah** [monuyadav016/Saavn-Downloader#26]
eg: https://www.jiosaavn.com/album/kabir-singh/kLG-OKbVmvM_

**Comment by faheembhati** [comment]
They've changed site's UI, that's why it no longer works. @monuyadav016, could you please fix it?

**Comment by monuyadav016** [comment]
> They've updated site's UI, that's why it no longer works. @monuyadav016, could you please fix it?

Thank you for reporting this. I'll look into fixing it soon.

**Comment by monuyadav016** [comment]
@cs-mshah @faheembhati A small fix for downloading albums and playlist has been done. I'll have to figure out a fix for artist and individual songs. Download and update the scripts.

**Comment by monuyadav016** [comment]
https://github.com/monuyadav016/Saavn-Downloader/issues/27#issuecomment-646726927
