### ISSUE TITLE
Profile Songs not being downloaded

### ISSUE THREAD

**Issue by kartikeyvaish** [monuyadav016/Saavn-Downloader#30]
Songs from Account are not being downloaded

**Comment by sankalpgaikwad** [comment]
JioSaavn site is updated so we are not able to download.

**Comment by kartikeyvaish** [comment]
Yes I know...Actually my JioSaavn account subscription expired and I wanted to download all the songs and save it into my device
The scipts that the owner provided helped me to download them.
Actually I copied the source code of the page where all my songs were there
Then I extracted all the links from it and pasted it into a text file.
After that I usedd this text file to download all the songs.
Noo Login Nothing..Simple!

**Comment by monuyadav016** [comment]
I really don't see what part of it is not working. You have to upload at least a screenshot or error you got and the command you used.

**Comment by kartikeyvaish** [comment]
I am attatching a screenshot of the Power Shell Where I executed the command
donwload_reloaded.py -user -a
![Final](https://user-images.githubusercontent.com/55032587/87278018-369c2d00-c503-11ea-976a-79569c8dfb2c.png)

**Comment by kartikeyvaish** [comment]
It says DONE but no songs are being downloaded

**Comment by terminal77** [comment]
@monuyadav016 This is the error Im getting when downloading the playlist or albums from profile.

`python3 download_reloaded.py -user -a`

```
Traceback (most recent call last):
  File "download_reloaded.py", line 78, in <module>
    obj.run()
  File "download_reloaded.py", line 41, in run
    account.start_download_album()
  File "/home/nadmin/Saavn-Downloader/scripts/saavnaccount.py", line 279, in start_download_album
    library_json, session = self.getLibrarySession()
TypeError: 'bool' object is not iterable
```

**Comment by kartikeyvaish** [comment]
Yes there is some error while downloading songs from a Profile..
Other than profile section everything else is working for me. :)

**Comment by terminal77** [comment]
Maybe this is related to new OTP that Saavn sends via email on new logins.

**Comment by kartikeyvaish** [comment]
You can close this issue as the site is Updated.
It requires OTP Login so you cannot download songs from Profile.
Other than that everything is working as expected.!

**Comment by monuyadav016** [comment]
OTP validation not only breaks features relating to profile songs download but also the one which allows for creation of temporary fake accounts. Everyone can still download their playlists since they are public by default.
