### ISSUE TITLE
Some dependencies missing

### ISSUE THREAD

**Issue by parampavar** [monuyadav016/Saavn-Downloader#34]
The following dependencies are not available to be installed from pip

get==2019.4.13
post==2019.4.13
request==2019.4.13

These packages have been removed by the developer.

Please add your local copy to this repo. 

Thanks

**Comment by parampavar** [comment]
https://quabr.com/48333990/what-is-the-story-behind-russianidiot-on-pypi

These packages are malicious. Please replace with equivalent ones

**Comment by monuyadav016** [comment]
@parampavar Thank you for your response. I wasn't able to update it earlier.
