### ISSUE TITLE
not working, getting this error

### ISSUE THREAD

**Issue by askfriends** [monuyadav016/Saavn-Downloader#36]
**hi..

when i install requirements on colab i got this red line error in the bottom**

```
"ERROR: Could not find a version that satisfies the requirement get==2019.4.13 (from -r requirements.txt (line 9)) (from versions: none)
ERROR: No matching distribution found for get==2019.4.13 (from -r requirements.txt (line 9))"
```

**also when i run the main command got this error**

![Opera Snapshot_2020-08-19_000047_colab research google com](https://user-images.githubusercontent.com/2517219/90554857-e7a38080-e1af-11ea-91a7-99644e230bc5.png)

**Comment by monuyadav016** [comment]
@askfriends  Issue has been fixed in the latest update
