### ISSUE TITLE
Add argument for download location

### ISSUE THREAD

**Issue by terminal77** [monuyadav016/Saavn-Downloader#4]
Hey bud,
I want to make a docker image for this however its hard to do with the current implementation where downloaded songs are placed in the same directory as where this repo is cloned. Can you please add a -outFolder argument that can be used to specify the download location. e.g.: `python Download.py -artist -song -outFolder \etc\Saavn` will save downloaded files in `\etc\saavn`
Cheers

**Comment by monuyadav016** [comment]
Sorry I haven't been active for so long. You can now specify the output path for the with the [-o or --outFolder](https://github.com/monuyadav016/Saavn-downloader#choose-output-folder-path-with-the--o-or---outfolder-argument-the-output-path-must-be-absolute-path-and-not-relative) argument. Replace your Download.py file or the entire repository with the new one to see the changes.

**Comment by terminal77** [comment]
Thank you very much for adding this quickly.
