### ISSUE TITLE
Playlist and other URLs as an argument

### ISSUE THREAD

**Issue by terminal77** [monuyadav016/Saavn-Downloader#5]
Hey bud,
I'm back with another request. Is it possible to add the arguments to pass the URL of song/playlist/album/artist directly to the `download.py` instead of it asking in the next step. Essentially I want to run it as a cron job so it'll be easier to script it that way. It would look something like this:

For playlist/song:
`python3 Download.py -o /home/monu/Desktop/ -url https://www.jiosaavn.com/album/tum-hi-aana-from-marjaavaan/j9bfphC2728_`

For Album/Artist:
`python Download.py -artist -album -url https://www.jiosaavn.com/artist/babbal-rai-albums/pRd5ZTGrLv8_`

Thanks again for being so responsive on this project.

**Comment by monuyadav016** [comment]
I fixed this earlier but was not able mention it in the issues. To follow up with this post use Saavn-Download-Reloaded which is downloaded along with this repo. Now you can specify the url in the command line arguments itself. Now you need not explicitly specify the type of url you intend to download. Also you can specify a file with urls https://github.com/monuyadav016/Saavn-Downloader/issues/8
```
$ python download_reloaded.py --url URL
```

For those with Jiosaavn account can specify the username and password in the command line arguments along with the type of downloads. Command to download playlists from account
```
$ python download_reloaded.py -user -e EMAIL -p PASSWORD --p
```
Command to download albums from account
```
$ python download_reloaded.py -user -e EMAIL -p PASSWORD --a
```
Command to download songs from account
```
$ python download_reloaded.py -user -e EMAIL -p PASSWORD --a
```

**Comment by terminal77** [comment]
Perfect, Thank you much.
