### ISSUE TITLE
Add option to remove songs from playlist on Saavn

### ISSUE THREAD

**Issue by terminal77** [monuyadav016/Saavn-Downloader#6]
Also to add to #5 , since you are quite familiar with Saavn APIs. Is it possible to pass an additional argument that will remove all the songs from playlist after download? The idea here is that I will be running this as a cron job where it will download songs from a playlist, once the songs are downloaded it will remove those from playlist and then I can add any new songs to playlist from Saavn app and this will only download new songs on next run. I know it only downloads new songs by default but for my use case the downloaded songs will be moved from download location to Music storage. e.g:

`python3 Download.py -o /home/monu/Desktop/ -url https://www.jiosaavn.com/album/tum-hi-aana-from-marjaavaan/j9bfphC2728_ -clearplaylist`

**Comment by monuyadav016** [comment]
This can have unintended consequences if one of the songs fail to download causing error and then we may end up with empty playlist. Will probably look into this later.

**Comment by terminal77** [comment]
Thank you, we can probably add a check, here I'll write down the logic I had in mind:
- Cron runs
- pydownloader retrieves the list of songs in playlist, saves the number of songs on a variable
- Tries to download songs, keeps a counter of successful song downloads
- if (number of songs downloaded = number of songs in playlist)
-- Remove all the songs from playlist
- else
-- Write info to a log file and exit (Do not remove any songs from playlist in this case)
