### ISSUE TITLE
[Request] Input list of album urls

### ISSUE THREAD

**Issue by PrathamH** [monuyadav016/Saavn-Downloader#8]
So I tried this program, works awesome. I just request a feature to input a list of album urls so that the program continues without asking for url of each album. 
This can be implemented for artists too (list of artist urls)...
I found an issue in reloaded version tho will post it in next issue post.

**Comment by monuyadav016** [comment]
Thank you for your support. I have updated the updated the reloaded version for accepting a file with urls separated by newline. With this you should be able to specify the file path (relative or absolute) to the program and it should continue downloading all. You can use the below command to achieve this
```sh
$ python download_reloaded.py --file PATH_TO_THE_URLS_FILE
```
Also ensure that the urls are separated by newline and that their are no blank lines in between. Further updates will only be added to the reloaded version where it'll be easier to write tests, create gui  and api later on. The download quality issue with it has been fixed.

**Comment by PrathamH** [comment]
From checking both versions norm and reloaded, can you please try program again... 
after update it seems everything is broken. I am unable to download anything.
gives output:

"Enter the url: https://www.jiosaavn.com/album/bajirao-mastani/s3tDZwdRQ4I_
...
...
Please paste link of album or playlist

DONE"

from older version...
and new version too gives this error:

"Enter the URL : https://www.jiosaavn.com/album/bajirao-mastani/s3tDZwdRQ4I_
Traceback (most recent call last):
  File "/content/Saavn-Downloader/Saavn-Download-Reloaded/download_reloaded.py", line 77, in <module>
    obj.run()
  File "/content/Saavn-Downloader/Saavn-Download-Reloaded/download_reloaded.py", line 68, in run
    album.start_download()
  File "/content/Saavn-Downloader/Saavn-Download-Reloaded/album.py", line 61, in start_download
    self.getAlbumID()
  File "/content/Saavn-Downloader/Saavn-Download-Reloaded/album.py", line 29, in getAlbumID
    self.albumID = soup.select(".play")[0]["onclick"]
IndexError: list index out of range"

**Comment by monuyadav016** [comment]
I hope the issue has been resolved because everything is good on my side.
