### ISSUE TITLE
[Issue] Reloaded version downloads low quality

### ISSUE THREAD

**Issue by PrathamH** [monuyadav016/Saavn-Downloader#9]
Sorry if I'm unable to use the new version correctly but as a normal user I tried download_reloaded.py for some reason it downloaded at low quality... like I saw 3-4 mb songs getting downloaded. I tried older download.py worked flawlessly with 11-12 mb songs.

**Comment by monuyadav016** [comment]
My mistake, I accidently left the download quality set at 96kbps bitrate while testing. You can fix it with by uncommenting the below line in download_manager.py file. This will be fixed in the next hour when I push the next update.
`# dec_url = dec_url.replace('_96.mp4', '_320.mp4')`

**Comment by PrathamH** [comment]
Thanks for your amazing work in here. Keep it up...
